### ISSUE TITLE
Environment issues on Windows 11

### ISSUE THREAD

**Issue by MarsEverythingTech** [Zheng-Chong/CatVTON#12]
Hello,

I was trying to install the repo locally on my PC, however, I was unable to perform the last step: pip install git+https://github.com/facebookresearch/detectron2@main#subdirectory=projects/DensePose
as it is giving me an error in red: error: could not build wheels for detectron2, which is required to install pyproject.toml-based projects
I've been told to install VS Build Tools but that didn't help. 

Thanks in advance

**Comment by Zheng-Chong** [comment]
If your PC is Windows OS, have you checked https://github.com/Zheng-Chong/CatVTON/issues/8 ？

**Comment by MarsEverythingTech** [comment]
> If your PC is Windows OS, have you checked #8 ？

Yes, I am on Windows 11, I also checked #8, but I am getting this error:
LoadAutoMasker
CatVTON
AutoMasker
LoadCatVTONPipeline
Nodes that have failed to load will show as red on the graph.

**Comment by Zheng-Chong** [comment]
What about https://github.com/Zheng-Chong/CatVTON/issues/7 , it seems you have similar situation?

**Comment by Zheng-Chong** [comment]
2.Download [ComfyUI-CatVTON.zip](https://github.com/Zheng-Chong/CatVTON/releases/download/ComfyUI/ComfyUI-CatVTON.zip) and unzip it in the custom_nodes folder under your ComfyUI project (clone from [ComfyUI](https://github.com/comfyanonymous/ComfyUI)).

**Comment by MarsEverythingTech** [comment]
> 2.Download [ComfyUI-CatVTON.zip](https://github.com/Zheng-Chong/CatVTON/releases/download/ComfyUI/ComfyUI-CatVTON.zip) and unzip it in the custom_nodes folder under your ComfyUI project (clone from [ComfyUI](https://github.com/comfyanonymous/ComfyUI)).

Yes, I already done that, but it didn't work

**Comment by Zheng-Chong** [comment]
> > 2.Download [ComfyUI-CatVTON.zip](https://github.com/Zheng-Chong/CatVTON/releases/download/ComfyUI/ComfyUI-CatVTON.zip) and unzip it in the custom_nodes folder under your ComfyUI project (clone from [ComfyUI](https://github.com/comfyanonymous/ComfyUI)).
> 
> Yes, I have already done that, but it didn't work

After that. have you restarted the ComfyUI?

**Comment by MarsEverythingTech** [comment]
> > > 2.Download [ComfyUI-CatVTON.zip](https://github.com/Zheng-Chong/CatVTON/releases/download/ComfyUI/ComfyUI-CatVTON.zip) and unzip it in the custom_nodes folder under your ComfyUI project (clone from [ComfyUI](https://github.com/comfyanonymous/ComfyUI)).
> > 
> > 
> > Yes, I have already done that, but it didn't work
> 
> After that. have you restarted the ComfyUI?

Yes I did.

**Comment by Zheng-Chong** [comment]
I'm very sorry that we can't solve your problem, but we don't have a test machine running on WindowsOS and can't reproduce your problem, so we can't provide further help.
I saw that you also raised the same problem in another repo Comfyui-catvton expecially for WindowOS, maybe it can be solved there.

**Comment by MarsEverythingTech** [comment]
> I'm very sorry that we can't solve your problem, but we don't have a test machine running on WindowsOS and can't reproduce your problem, so we can't provide further help. I saw that you also raised the same problem in another repo Comfyui-catvton expecially for WindowOS, maybe it can be solved there.

How about installing it locally, I am just having trouble with the last step and is giving me this error:

note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for detectron2
  Running setup.py clean for detectron2
Successfully built detectron2-densepose
Failed to build detectron2
ERROR: Could not build wheels for detectron2, which is required to install pyproject.toml-based projects

**Comment by Zheng-Chong** [comment]
> > I'm very sorry that we can't solve your problem, but we don't have a test machine running on WindowsOS and can't reproduce your problem, so we can't provide further help. I saw that you also raised the same problem in another repo Comfyui-catvton expecially for WindowOS, maybe it can be solved there.
> 
> How about installing it locally, I am just having trouble with the last step and is giving me this error:
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for detectron2 Running setup.py clean for detectron2 Successfully built detectron2-densepose Failed to build detectron2 ERROR: Could not build wheels for detectron2, which is required to install pyproject.toml-based projects

Another issue in detectron2 repo provides a solution, maybe you can try it. https://github.com/facebookresearch/detectron2/issues/5008#issuecomment-1787796388

**Comment by MarsEverythingTech** [comment]
> > > I'm very sorry that we can't solve your problem, but we don't have a test machine running on WindowsOS and can't reproduce your problem, so we can't provide further help. I saw that you also raised the same problem in another repo Comfyui-catvton expecially for WindowOS, maybe it can be solved there.
> > 
> > 
> > How about installing it locally, I am just having trouble with the last step and is giving me this error:
> > note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for detectron2 Running setup.py clean for detectron2 Successfully built detectron2-densepose Failed to build detectron2 ERROR: Could not build wheels for detectron2, which is required to install pyproject.toml-based projects
> 
> Another issue in detectron2 repo provides a solution, maybe you can try it. [facebookresearch/detectron2#5008 (comment)](https://github.com/facebookresearch/detectron2/issues/5008#issuecomment-1787796388)

Would using a Docker help?

**Comment by Zheng-Chong** [comment]
is `pip install git+https://github.com/facebookresearch/detectron2.git@v0.6#subdirectory=projects/DensePose` the command you use?

**Comment by MarsEverythingTech** [comment]
> is `pip install git+https://github.com/facebookresearch/detectron2.git@v0.6#subdirectory=projects/DensePose` the command you use?
> 
> #5 reported the installment error of detectron2 in Win.

Yes, I followed the step and got them installed. However, when running:
python app.py --output_dir="resource/demo/output" --mixed_precision="bf16" --allow_tf32 

I get the following error:
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\'
C:\Users\miniconda3\envs\catvton\lib\site-packages\torch\utils\cpp_extension.py:383: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Traceback (most recent call last):
  File "C:\CatVTON\app.py", line 12, in <module>
    from model.cloth_masker import AutoMasker, vis_mask
  File "C:\CatVTON\model\cloth_masker.py", line 9, in <module>
    from model.SCHP import SCHP  # type: ignore
  File "C:\CatVTON\model\SCHP\__init__.py", line 1, in <module>
    from model.SCHP import networks
  File "C:\CatVTON\model\SCHP\networks\__init__.py", line 3, in <module>
    from model.SCHP.networks.AugmentCE2P import resnet101
  File "C:\CatVTON\model\SCHP\networks\AugmentCE2P.py", line 21, in <module>
    from model.SCHP.modules import InPlaceABNSync
  File "C:\CatVTON\model\SCHP\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "C:\CatVTON\model\SCHP\modules\bn.py", line 10, in <module>
    from .functions import *
  File "C:\CatVTON\model\SCHP\modules\functions.py", line 10, in <module>
    _backend = load(name="inplace_abn",
  File "C:\Users\miniconda3\envs\catvton\lib\site-packages\torch\utils\cpp_extension.py", line 1308, in load
    return _jit_compile(
  File "C:\Users\miniconda3\envs\catvton\lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\miniconda3\envs\catvton\lib\site-packages\torch\utils\cpp_extension.py", line 1810, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "C:\Users\miniconda3\envs\catvton\lib\site-packages\torch\utils\cpp_extension.py", line 2199, in _write_ninja_file_to_build_library
    cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
  File "C:\Users\miniconda3\envs\catvton\lib\site-packages\torch\utils\cpp_extension.py", line 1980, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range

**Comment by Zheng-Chong** [comment]
It looks like your torch and cuda versions conflict, maybe you can google the specific error message

**Comment by MarsEverythingTech** [comment]
> No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin'
> C:\Users\miniconda3\envs\catvton\lib\site-packages\torch\utils\cpp_extension.py:383: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
> warnings.warn(f'Error checking compiler version for {compiler}: {error}')
> Traceback (most recent call last):
> File "C:\CatVTON\app.py", line 12, in
> from model.cloth_masker import AutoMasker, vis_mask
> File "C:\CatVTON\model\cloth_masker.py", line 9, in
> from model.SCHP import SCHP # type: ignore
> File "C:\CatVTON\model\SCHP__init__.py", line 1, in
> from model.SCHP import networks
> File "C:\CatVTON\model\SCHP\networks__init__.py", line 3, in
> from model.SCHP.networks.AugmentCE2P import resnet101
> File "C:\CatVTON\model\SCHP\networks\AugmentCE2P.py", line 21, in
> from model.SCHP.modules import InPlaceABNSync
> File "C:\CatVTON\model\SCHP\modules__init__.py", line 1, in
> from .bn import ABN, InPlaceABN, InPlaceABNSync
> File "C:\CatVTON\model\SCHP\modules\bn.py", line 10, in
> from .functions import *
> File "C:\CatVTON\model\SCHP\modules\functions.py", line 10, in
> _backend = load(name="inplace_abn",
> File "C:\Users\miniconda3\envs\catvton\lib\site-packages\torch\utils\cpp_extension.py", line 1308, in load
> return _jit_compile(
> File "C:\Users\miniconda3\envs\catvton\lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
> _write_ninja_file_and_build_library(
> File "C:\Users\miniconda3\envs\catvton\lib\site-packages\torch\utils\cpp_extension.py", line 1810, in _write_ninja_file_and_build_library
> _write_ninja_file_to_build_library(
> File "C:\Users\miniconda3\envs\catvton\lib\site-packages\torch\utils\cpp_extension.py", line 2199, in _write_ninja_file_to_build_library
> cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
> File "C:\Users\miniconda3\envs\catvton\lib\site-packages\torch\utils\cpp_extension.py", line 1980, in _get_cuda_arch_flags
> arch_list[-1] += '+PTX'
> IndexError: list index out of range

Could you please help me how to fix it?

**Comment by MarsEverythingTech** [comment]
> It looks like your torch and cuda versions conflict, maybe you can google the specific error message

Could you please help me fix it?

**Comment by MarsEverythingTech** [comment]
> It looks like your torch and cuda versions conflict, maybe you can google the specific error message

Ok now I am getting this error:

C:\Users\miniconda3\envs\catvton\lib\site-packages\torch\utils\cpp_extension.py:380: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
C:\Users\miniconda3\envs\catvton\lib\site-packages\torch\utils\cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "C:\CatVTON\app.py", line 12, in <module>
    from model.cloth_masker import AutoMasker, vis_mask
  File "C:\CatVTON\model\cloth_masker.py", line 9, in <module>
    from model.SCHP import SCHP  # type: ignore
  File "C:\CatVTON\model\SCHP\__init__.py", line 1, in <module>
    from model.SCHP import networks
  File "C:\CatVTON\model\SCHP\networks\__init__.py", line 3, in <module>
    from model.SCHP.networks.AugmentCE2P import resnet101
  File "C:\CatVTON\model\SCHP\networks\AugmentCE2P.py", line 21, in <module>
    from model.SCHP.modules import InPlaceABNSync
  File "C:\CatVTON\model\SCHP\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "C:\CatVTON\model\SCHP\modules\bn.py", line 10, in <module>
    from .functions import *
  File "C:\CatVTON\model\SCHP\modules\functions.py", line 10, in <module>
    _backend = load(name="inplace_abn",
  File "C:\Users\shrou\miniconda3\envs\catvton\lib\site-packages\torch\utils\cpp_extension.py", line 1312, in load
    return _jit_compile(
  File "C:\Users\shrou\miniconda3\envs\catvton\lib\site-packages\torch\utils\cpp_extension.py", line 1722, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\shrou\miniconda3\envs\catvton\lib\site-packages\torch\utils\cpp_extension.py", line 1821, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "C:\Users\shrou\miniconda3\envs\catvton\lib\site-packages\torch\utils\cpp_extension.py", line 2246, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "C:\Users\shrou\miniconda3\envs\catvton\lib\site-packages\torch\utils\cpp_extension.py", line 2382, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "C:\Users\shrou\miniconda3\envs\catvton\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\shrou\miniconda3\envs\catvton\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

**Comment by Zheng-Chong** [comment]
I'm sorry, but the environment setup is quite complex. It involves not only the operating system but also graphics card drivers and dependencies of other packages. I find it difficult to provide specific help to fix the bug for you. 

I will keep this issue open to see if anyone else encounters a similar problem.

**Comment by MarsEverythingTech** [comment]
> I'm sorry, but the environment setup is quite complex. It involves not only the operating system but also graphics card drivers and dependencies of other packages. I find it difficult to provide specific help to fix the bug for you.
> 
> I will keep this issue open to see if anyone else encounters a similar problem.

Hello, I have fixed that error by installing other packages for VS Build Tools, however, I am having this issue:
\miniconda3\envs\catvton\lib\site-packages\torch\utils\cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].

Then I did: set TORCH_CUDA_ARCH_LIST="8.6"
but returned with another error: 
File "C:\Users\miniconda3\envs\catvton\lib\site-packages\torch\utils\cpp_extension.py", line 1998, in _get_cuda_arch_flags
    raise ValueError(f"Unknown CUDA arch ({arch}) or GPU not supported")
ValueError: Unknown CUDA arch ("8.6") or GPU not supported

**Comment by justinjohn0306** [comment]
I was able to get it working on windows but had to do a few adjustments in order to successfully build the modules

<img width="1919" alt="image" src="https://github.com/user-attachments/assets/40389432-1c7f-4841-9428-ef23d0cc583f">

**Comment by MarsEverythingTech** [comment]
> I was able to get it working on windows but had to do a few adjustments in order to successfully build the modules
> 
> 
> 
> <img width="1919" alt="image" src="https://github.com/user-attachments/assets/40389432-1c7f-4841-9428-ef23d0cc583f">
> 
>  

Amazing! Could you please provide me the steps on how you made it work?

Thanks in advance

**Comment by valaxy** [comment]
failed on win11 but with error:
```
Ninja is required to load C++ extensions
```
but in fact
```
pip install ninja
```
works

**Comment by dseditor** [comment]
For the "where cl" error,
Starting ComfyUI using “x64 Native Tools Command Prompt for VS 2022”，Do not using original cmd/powershell.
That's maybe the problem of the VC env settings in WindowsOS.
