### ISSUE TITLE
ModuleNotFoundError: No module named 'densepose'

### ISSUE THREAD

**Issue by walkingwithGod2017** [Zheng-Chong/CatVTON#40]
大佬，麻烦看下。之前我手动安装的densepose可以运行。
我今天同步你更新了densepose和SCHP之后的代码，再运行项目提示出错了。

(catvton) F:\AI\CatVTON>python app.py
Traceback (most recent call last):
  File "F:\AI\CatVTON\app.py", line 12, in <module>
    from model.cloth_masker import AutoMasker, vis_mask
  File "F:\AI\CatVTON\model\cloth_masker.py", line 10, in <module>
    from model.DensePose import DensePose  # type: ignore
  File "F:\AI\CatVTON\model\DensePose\__init__.py", line 12, in <module>
    from densepose import add_densepose_config
ModuleNotFoundError: No module named 'densepose'

**Comment by walkingwithGod2017** [comment]
> 大佬，麻烦看下。之前我手动安装的densepose可以运行。 我今天同步你更新了densepose和SCHP之后的代码，再运行项目提示出错了。
> 
> (catvton) F:\AI\CatVTON>python app.py Traceback (most recent call last): File "F:\AI\CatVTON\app.py", line 12, in from model.cloth_masker import AutoMasker, vis_mask File "F:\AI\CatVTON\model\cloth_masker.py", line 10, in from model.DensePose import DensePose # type: ignore File "F:\AI\CatVTON\model\DensePose__init__.py", line 12, in from densepose import add_densepose_config ModuleNotFoundError: No module named 'densepose'

OK，已经解决了，是那个densepose的最新代码用git没更新下来，我又重新克隆的，之后可以运行了。感谢大佬，同样建议大佬研究下视频的换装！！
