### ISSUE TITLE
Cannot load stable-diffusion-inpainting

### ISSUE THREAD

**Issue by merolaika** [Zheng-Chong/CatVTON#62]
(catvton_env) C:\MERIC\CatVTON>set CUDA_VISIBLE_DEVICES=0 && python app.py --output_dir="resource/demo/output" --mixed_precision="bf16" --allow_tf32
Fetching 10 files: 100%|████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 10010.27it/s]
Traceback (most recent call last):
  File "C:\MERIC\CatVTON\app.py", line 106, in <module>
    pipeline = CatVTONPipeline(
  File "C:\MERIC\CatVTON\model\pipeline.py", line 44, in __init__
    self.unet = UNet2DConditionModel.from_pretrained(base_ckpt, subfolder="unet").to(device, dtype=weight_dtype)
  File "C:\YapayZeka\pinokio\bin\miniconda\envs\catvton_env\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\YapayZeka\pinokio\bin\miniconda\envs\catvton_env\lib\site-packages\diffusers\models\modeling_utils.py", line 747, in from_pretrained
    unexpected_keys = load_model_dict_into_meta(
  File "C:\YapayZeka\pinokio\bin\miniconda\envs\catvton_env\lib\site-packages\diffusers\models\model_loading_utils.py", line 154, in load_model_dict_into_meta
    raise ValueError(
ValueError: Cannot load stable-diffusion-inpainting because conv_in.weight expected shape tensor(..., device='meta', size=(320, 9, 3, 3)), but got torch.Size([320, 4, 3, 3]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example.

**Comment by merolaika** [comment]
error
Could not parse server response: SyntaxError: Unexpected token 'I', "Internal S"... is not valid JSON

**Comment by Zheng-Chong** [comment]
([320, 4, 3, 3]) suggests that you are use a stable-diffusion T2I version rather than an inpainting version, maybe you can try to use another huggingface repo like https://huggingface.co/booksforcharlie/stable-diffusion-inpainting.
