### ISSUE TITLE
a modified CatVTON Comfyui node

### ISSUE THREAD

**Issue by pzc163** [Zheng-Chong/CatVTON#8]
Thanks for Autor's hard work, based on original project, I modified a new CatVTON Comfyui node and release on https://github.com/pzc163/Comfyui-CatVTON for more user friendly with Win OS user. And also i post a short blog on https://x.com/yangzhizheng1/status/1818197568293388578 for more and more people notice our work.

**Comment by Zheng-Chong** [comment]
Thank you for your support. I will add a link to this issue in README later to help other users in Windows environment to deploy ComfyUI.

------------------------------------------------------------
This issue will be kept and update to provide guidance for Win Users.
1. For Detectron2 or DensePose installment in Windows OS, refer to https://github.com/Zheng-Chong/CatVTON/issues/5.
2. Some Installation issues on Win11 https://github.com/Zheng-Chong/CatVTON/issues/12.
3. https://github.com/Zheng-Chong/CatVTON/issues/29.

**Comment by BarryyyDrew** [comment]
I just encountered a n issue
(Catvton) C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable>C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\run_nvidia_gpu.bat

(Catvton) C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-08-02 17:59:40.515309
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI
** Log path: C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   1.1 seconds: C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 32632 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2070 SUPER : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\web
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CatVTON\__init__.py", line 3, in <module>
    from .model.cloth_masker import AutoMasker as AM
  File "C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CatVTON\model\cloth_masker.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CatVTON module for custom nodes: No module named 'cv2'
### Loading: ComfyUI-Manager (V2.48.4)
### ComfyUI Revision: 2445 [369f459b] | Released on '2024-08-01'

It seems that it's the cv2 module issue,but i can correctly import cv2  in my virtual environment. So i have no idea what happened

**Comment by Zheng-Chong** [comment]
cv2 can be installed by pip install opencv-python in command line.

**Comment by faraztayari** [comment]
I have completed all the steps and encountered no errors, but when uploading the JSON file, I get the following error:
'When loading the graph, the following node types were not found:
LoadAutoMasker
LoadCatVTONPipeline
CatVTON
AutoMasker
Nodes that have failed to load will show as red on the graph.'"

**Comment by gafoart** [comment]
> I have completed all the steps and encountered no errors, but when uploading the JSON file, I get the following error: 'When loading the graph, the following node types were not found: LoadAutoMasker LoadCatVTONPipeline CatVTON AutoMasker Nodes that have failed to load will show as red on the graph.'"

I've the same issue

**Comment by urstruly4** [comment]
I have the same problem as the 2 above. any way to solve this issue when loading the workflow says:
Warning: Missing Node Types
When loading the graph, the following node types were not found:

LoadAutoMasker
CatVTON
AutoMasker
LoadCatVTONPipeline
No selected item
Nodes that have failed to load will show as red on the graph 

I have asked chatgpt  and tried everything it is suggesting and it is still not working. 

Will you be able to help me set this up properly, I am quite a noob and willing to pay for any help to have this set up!

**Comment by 13437021811** [comment]
我有和上面 2 个一样的问题。加载工作流时解决此问题的任何方法都显示：
警告：缺少节点类型
加载图形时，找不到以下节点类型：

LoadAutoMasker
CatVTON
AutoMasker
LoadCatVTONPipeline
No selected item
加载失败的节点将在图表上显示为红色

我已经询问了 chatgpt 并尝试了它所建议的一切，但它仍然无法正常工作。

你能帮我正确设置吗，我是个菜鸟，愿意为任何帮助付费来设置这个！

me too,the same issue

**Comment by Marketticker** [comment]
Same issue i feel this repo not really working tried all there workflows and combos , there is always files missing

**Comment by csurgajurgi** [comment]
mee too :(

**Comment by grape600** [comment]
同上 我要崩溃了

**Comment by kkkkkkg666** [comment]
wok我也是一直显示找不到节点类型

**Comment by ricardoponcio** [comment]
Same here, didnt solved yet?

**Comment by wantedrbk2** [comment]
CatVTON for comfyUI seems like is not working , its not visible in node manager

**Comment by xmu-linguoyu** [comment]
Does anyone have a new solution for this?
I'm also stuck with a missing node after all environments have been deployed.

**Comment by Art94** [comment]
Does this thing even work? 10 attempts on 10 different systems. Requirments seem to have been written by drunken raccoons. How is it possible to assemble it?

**Comment by saurabh0666** [comment]
this error coming, i cross check all the files its right only.. any suggestion

We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like /workspace/ComfyUI/models/CatVTON/sd-vae-ft-mse is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at '[https://huggingface.co/docs/diffusers/installation#offline-mode'](javascript:void(0);).

**Comment by jasonlinljs** [comment]
I have the same issue. So grateful for anybody giving a solution.

![Image](https://github.com/user-attachments/assets/00944eff-215c-4946-9b26-36eb662d496e)

**Comment by ErfinderDesRades** [comment]
I experienced the same issue. Coudl you solve it?

**Comment by AshG2026** [comment]
Did anyone managed to solve the missing nodes issue, or CatVTON just cannot be used in ComfyUI?

**Comment by jduartedj** [comment]
I also can't get this to run on WindowsOS. Maybe you can create a docker file to run this in docker with GPU support?
Would this run in WSL?
